sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker --version

  - docker build -q -t vfac/envdevphpbase:7.1-alpine-cli .

  - docker run --name php7.1-alpine-cli -d -v $PWD:/var/www/html vfac/envdevphpbase:7.1-alpine-cli

script:
  - docker exec php7.1-alpine-cli php -v
  - docker exec php7.1-alpine-cli sh -c "php -v | grep 7.1"
  - docker exec php7.1-alpine-cli composer --version
