sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker --version
  - docker build -q -t vfac/envdevphpbase:7.3-fpm .
  - docker run --name php7.3 -d -v $PWD:/var/www/html vfac/envdevphpbase:7.3-fpm
  - docker-compose -f test/7.3/docker-compose.yml up -d

script:
  - docker exec php7.3 php -v
  - docker exec php7.3 sh -c "php -v | grep 7.3"
  - docker exec php7.3 sh -c "php test/test.php |grep version"
  - docker exec php7.3 composer --version
  - curl -s localhost:8072/test.php |grep bcmath
