sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker --version

  - docker build -q -t vfac/envdevphpbase:7.2-alpine .

  - docker run --name php7.2-alpine-cli -d -v $PWD:/var/www/html vfac/envdevphpbase:7.2-alpine-cli

  - docker-compose -f test/7.2-alpine-cli/docker-compose.yml up -d

script:
  - docker exec php7.2-alpine-cli php -v
  - docker exec php7.2-alpine-cli sh -c "php -v | grep 7.2"
  - docker exec php7.2-alpine-cli sh -c "php test/test.php |grep version"
  - docker exec php7.2-alpine-cli composer --version
  - curl -s localhost:8172/test.php |grep bcmath
