sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x /usr/local/bin/docker-compose

  - docker --version
  - docker build -q -t vfac/envdevphpbase:7.0-cli .

script:
  - docker run --rm vfac/envdevphpbase:7.0-cli php -v
  - docker run --rm vfac/envdevphpbase:7.0-cli sh -c "php -v | grep 7.0"
  - docker run --rm vfac/envdevphpbase:7.0-cli composer --version
  - docker run --rm vfac/envdevphpbase:7.0-cli nodejs -v
  - docker run --rm vfac/envdevphpbase:7.0-cli npm -v
